const getters = {
  sidebar: (state) => state.app.sidebar,
  device: (state) => state.app.device,
  token: (state) => state.user.token,
  avatar: (state) => state.user.avatar,
  name: (state) => state.user.name,
  userId: (state) => state.user.userId,
  companyId: (state) => state.user.companyId,
  roles: (state) => state.user.roles,
  roleId: (state) => state.user.roleId,
  userRolesNames: (state) => state.user.userRolesNames,
  perms: (state) => state.user.perms,
  addRoutes: (state) => state.permission.addRoutes,
  permission_routes: (state) =>
    state.permission.routes ||
    JSON.parse(localStorage.getItem("accessedRoutes")),
  isScreenFull: (state) => state.user.isScreenFull, // 控制进入首页不是全屏
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  isLicenseEnabled: (state) => state.user.isLicenseEnabled,
  userInfo: (state) => state.user.userInfo,
  noticeData: (state) => state.ws.noticeData,
  unreadMsg: (state) => state.ws.unreadMsg,
  unreadCount: (state) => state.ws.unreadCount,
  studentList: (state) => state.ws.studentList,
  teaReply: (state) => state.ws.teaReply,
  roleType: (state) => state.user.roleType,
  theme: (state) => state.settings.theme,
  tableId: (state) => state.approval.tableId,
  isTried: (state) => state.approval.isTried,
  promoterDrawer: (state) => state.approval.promoterDrawer,
  flowPermission1: (state) => state.approval.flowPermission1,
  approverDrawer: (state) => state.approval.approverDrawer,
  approverConfig1: (state) => state.approval.approverConfig1,
  copyerDrawer: (state) => state.approval.copyerDrawer,
  copyerConfig1: (state) => state.approval.copyerConfig1,
  conditionDrawer: (state) => state.approval.conditionDrawer,
  conditionsConfig1: (state) => state.approval.conditionsConfig1,
};
export default getters;
